config/routes.rb
Semantic2::Application.routes.draw do

  root :to => "episodes#index"

  match "/episodis" => redirect('/')
  resources :episodes, :path => 'episodis'

  # Session routes
  match "/auth/:provider/callback" => "sessions#create"
  match "/desconnectar" => "sessions#destroy", :as => :signout

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  mount_uploader :file, EpisodeUploader
  mount_uploader :image, ImageUploader

  has_many :sponsorships
  has_many :sponsors, :through => :sponsorships
  has_many :taggables
  has_many :tags, :through => :taggables
  has_many :participations
  has_many :users, :through => :participations

  validates_presence_of :title
  validates :number, :numericality => { :only_integer => true, :greater_than_or_equal_to => 1 }, :presence => true
  validates_presence_of :file
  validates_presence_of :permalink
  validates_presence_of :image
end

app/models/participation.rb
class Participation < ActiveRecord::Base
  belongs_to :user
  belongs_to :episode
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  mount_uploader :logo, LogoUploader

  has_many :sponsorships
  has_many :episodes, :through => :sponsorships

  validates_presence_of :name
  validates_presence_of :logo
  validates :amount, :numericality => { :greater_than_or_equal_to => 0.0 }, :presence => true
end

app/models/sponsorship.rb
class Sponsorship < ActiveRecord::Base
  belongs_to :episode
  belongs_to :sponsor
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggables
  has_many :episodes, :through => :taggables

  validates_presence_of :title
end

app/models/taggable.rb
class Taggable < ActiveRecord::Base
  belongs_to :episode
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :participations
  has_many :episodes, :through => :participations

  validates_presence_of :name

  def self.create_from_oauth!(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["user_info"]["name"]
      user.dump = auth.to_json
      user.screen_name = auth["user_info"]["nickname"]
      user.avatar_url = auth["user_info"]["image"]
      user.location = auth["user_info"]["location"]
      user.description = auth["user_info"]["description"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @episodes }
    end
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
    @episode = Episode.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/new
  # GET /episodes/new.json
  def new
    @episode = Episode.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @episode }
    end
  end

  # GET /episodes/1/edit
  def edit
    @episode = Episode.find(params[:id])
  end

  # POST /episodes
  # POST /episodes.json
  def create
    @episode = Episode.new(params[:episode])

    respond_to do |format|
      if @episode.save
        format.html { redirect_to @episode, notice: 'Episode was successfully created.' }
        format.json { render json: @episode, status: :created, location: @episode }
      else
        format.html { render action: "new" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /episodes/1
  # PUT /episodes/1.json
  def update
    @episode = Episode.find(params[:id])

    respond_to do |format|
      if @episode.update_attributes(params[:episode])
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy

    respond_to do |format|
      format.html { redirect_to episodes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_from_oauth!(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @episodes.each do |episode| %>
  <tr>
    <td><%= link_to 'Show', episode %></td>
    <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
    <td><%= link_to 'Destroy', episode, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title><%= content_for(:title) || "Podcast Semàntic" %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag    "application" %>

  <%= javascript_include_tag "application", "http://use.typekit.com/dbs0wlf.js" %>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <%= csrf_meta_tags %>
</head>
<body class="tk-museo-slab">
<nav>
  <ul>
    <li><a href="/" title="Home page">Podcast</a></li>
    <li><a href="/membres" title="Home page">Membres</a></li>
    <li><a href="/patrocinadors" title="Tots els patrocinadors de Semàntic">Patrocinadors</a></li>
    <li><a href="/que-es-semantic" title="Informació sobre el Podcast">Què és semàntic</a></li>
  </ul>
</nav>
<div id="container">
  <header>
    <h1>Semàntic podcast</h1>
  </header>

  <div id="main" role="main">
    <%= yield %>
  </div>

  <footer>

  </footer>
</div> <!--! end of #container -->

</body>
</html>